name: Maintenance

on:
  schedule:
    - cron: "0 0 1 */3 *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Maintenance on $(date)"
          commit_options: "--allow-empty"
